name    'zauberpony-froxlor'
version '0.1.0'
source 'git://github.com/zauberpony/puppet-froxlor.git'
author 'Elmar Athmer'
license 'Apache License, Version 2.0'
summary 'Puppet module for froxlor control panel'
description 'Install and configure froxlor and dependent services.'
project_page 'http://github.com/zauberpony/puppet-froxlor'

## Add dependencies, if any:
# dependency 'username/name', '>= 1.2.0'
dependency 'puppetlabs/apache', '>= 0.11.0'
dependency 'puppetlabs/apt', '>= 1.4.1'
dependency 'puppetlabs/mysql', '>= 2.2.1'
dependency 'puppetlabs/stdlib', '>= 4.1.0'
dependecny 'runthebusiness/mysqlexec', '>= 1.0.2'
